[package]
name = "math"
version = "0.1.0"
edition = "2021"

[lib]
name="math"
crate-type=["rlib","cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
